language: cpp
compiler:
  - gcc
  - clang
env:
  - PARAM_THREADS="--enable-threads --with-python --with-qt --with-qt5 --with-working-locale"
    CXXFLAGS="" SWIG_FLAGS=""
  - PARAM_THREADS="--enable-threads --with-python --with-qt --with-qt5 --with-working-locale"
    CXXFLAGS="-DUNICODE" SWIG_FLAGS="-DUNICODE"
  - PARAM_THREADS="--disable-threads --with-python --with-qt --with-qt5 --with-working-locale"
    CXXFLAGS="" SWIG_FLAGS=""
  - PARAM_THREADS="--disable-threads --with-python --with-qt --with-qt5 --with-working-locale"
    CXXFLAGS="-DUNICODE" SWIG_FLAGS="-DUNICODE"
  - PARAM_THREADS="--enable-threads --with-python --with-qt --with-qt5 --with-iconv"
    CXXFLAGS="" SWIG_FLAGS=""
  - PARAM_THREADS="--enable-threads --with-python --with-qt --with-qt5 --with-iconv"
    CXXFLAGS="-DUNICODE" SWIG_FLAGS="-DUNICODE"
  - PARAM_THREADS="--disable-threads --with-python --with-qt --with-qt5 --with-iconv"
    CXXFLAGS="" SWIG_FLAGS=""
  - PARAM_THREADS="--disable-threads --with-python --with-qt --with-qt5 --with-iconv"
    CXXFLAGS="-DUNICODE" SWIG_FLAGS="-DUNICODE"
  - PARAM_THREADS="--enable-threads --with-python --with-qt --with-qt5 --with-working-locale"
    CXXFLAGS="-std=c++98" SWIG_FLAGS=""
  - PARAM_THREADS="--enable-threads --with-python --with-qt --with-qt5 --with-working-locale"
    CXXFLAGS="-std=c++0x" SWIG_FLAGS=""
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -q swig python libqt4-dev qtbase5-dev
before_script:
  - sh ./scripts/fix-timestamps.sh
  - mkdir objdir
  - cd objdir
script: ../configure $PARAM_THREADS CXXFLAGS="$CXXFLAGS"
  SWIG_FLAGS="$SWIG_FLAGS"
  && make
  && make check
after_failure:
  - cat config.log
  - cat tests/testsuite.log
branches:
  only:
    - master
notifications:
  recipients:
    - vhaisman@gmail.com
  email:
    on_success: always
    on_failure: always
